# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yYGmGNkl_R4uxXbECjDrS_w3tI67Exes
"""

def solution(n, lost, reserve):
    # 문제에서는 정상적 사람, 도난당한 사람, 여분이 있는데 도난당한사람(정상적 사람이 됨)이 있음.
    # 이를 구분하기 위해 집합 set()함수를 사용할 수 있다.
    
    
    real_reserve = set(reserve) - set(lost) #여벌 진짜 있는사람 
    real_lost = set(lost) - set(reserve) #체육복이 아에 없는사람 (여분-도난은 포함x)
    answer = n - len(real_lost) #일단 체육복 문제없는 사람의 수 answer.

    for i in real_reserve: #앞뒤의 사람과 비교하여 겹치면 빌려주기! >문제없는 사람이 생김.
        if i - 1 in real_lost:
            real_lost.remove(i - 1)
            answer += 1
        elif i + 1 in real_lost:
            real_lost.remove(i + 1)
            answer += 1
    
    return answer

